project_id = "hedxxbsieoazrmbayzab"

# Edge Functions - Configurações
[functions]

  [functions.create-checkout]
    verify_jwt = true
  [functions.check-subscription]
    verify_jwt = true
  [functions.customer-portal]
    verify_jwt = true
  [functions.create-gift-checkout]
    verify_jwt = true
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.asaas-webhook]
    verify_jwt = false
[functions.send-push-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-push-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-push-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-push-notification/*.html" ]

[functions.send-verification-code]
enabled = true
verify_jwt = false
import_map = "./functions/send-verification-code/deno.json"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://2557dcd9-8c67-4fba-aafb-919ffbc2a87c.lovableproject.com/**", "https://2557dcd9-8c67-4fba-aafb-919ffbc2a87c.sandbox.lovable.dev/**", "https://a0d37d1a-70ae-4032-8cd6-184bce575d5b.lovableproject.com/**", "https://bb1df22e-d6c8-456d-a48e-a14a91b32b53.lovableproject.com/**", "https://cute-auth-hub.lovable.app/**", "https://github-project-grabber-go.lovable.app/**", "https://id-preview--2557dcd9-8c67-4fba-aafb-919ffbc2a87c.lovable.app/**", "https://id-preview--2557dcd9-8c67-4fba-aafb-919ffbc2a87c.preview.lovable.dev/**", "https://id-preview--a0d37d1a-70ae-4032-8cd6-184bce575d5b.lovable.app/**", "https://id-preview--bb1df22e-d6c8-456d-a48e-a14a91b32b53.lovable.app/**", "https://live-ai-chatter.lovable.app/**", "https://preview--cute-auth-hub.lovable.app/**", "https://preview--github-project-grabber-go.preview.lovable.dev/**", "https://preview--live-ai-chatter.lovable.app/**", "https://ominous-parakeet-v66xwj759p9rhxvqp-8080.app.github.dev/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
